### PR TITLE
add sha256 hash check for powershell

### LINKED ISSUE #2: Powershell: check the SHA256 sum with the SHA256SUMS file
Powershell: check the SHA256 sum with the SHA256SUMS file similar we have for MAC and LINUX

### PR DESCRIPTION
**Pull request by developer-guy**
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>

Fixes #2 

> https://stackoverflow.com/questions/63396620/how-can-i-compare-a-files-sha256-hash-in-powershell-to-a-known-value

### CODE REVIEW

**Comment by cpanato** [comment]
thanks for a quick contribution, we need to refactor a bit the SHA256SUMS contains all the files and not just one

see https://github.com/cpanato/vault-installer/actions/runs/3740062309/jobs/6348045175 it returns false but it passes the check :/

**Comment by developer-guy** [comment]
is there any update on this @cpanato 👋

**Comment by cpanato** [comment]
@developer-guy can you please rebase?

**Comment by developer-guy** [comment]
of course my friend!

**Review by cpanato — APPROVED** [review]

**Comment by cpanato** [comment]
thank you!

**Pull request merged**
